Train final nf1 model
WayScience/NF1_SchwannCell_data_analysis pull request #33
Opened 2024-05-21 15:42 UTC by MattsonCam

In this pr, the final nf1 model was trained and the resulting data was stored for later evaluation. Please let me know if you have any suggestions.

2024-05-21 16:49 UTC, jenna-tomkinson requested changes
Super exciting to finally get to a final model! I am requesting changes as I see in the `classify_genotypes.py` that you only use the feature-selected data from Plate 4 and just normalized from the rest of the plates. Based on the title of the notebook, it sounds like you want to use feature-selected data for all plates. Once you confirm that, then I can do a quick re-review and approve!

2024-05-21 16:49 UTC, jenna-tomkinson commented on 1.train_models/classify_genotypes/nbconverted/classify_genotypes.py
> +plate4df["Metadata_Plate"] = "Plate_4"
Recommend adding code comments here regarding that you are only including control wells from Plate 4 in the training and testing splits. As well, a comment on why you needed to add Plate_4 in the Metadata_Plate column, is this due to it being missing? If so, please add an issue to the image analysis repo so I possibly can make a fix for it if necessary.

2024-05-21 16:49 UTC, jenna-tomkinson commented on 1.train_models/classify_genotypes/nbconverted/classify_genotypes.py
> +plate4df_path = pathlib.Path(root_dir / "nf1_painting_repo/3.processing_features/data/single_cell_profiles/Plate_4_sc_feature_selected.parquet").resolve(strict=True)
Why do you only use the feature-selected parquet file for Plate_4 but not the rest of the plates? For the rest of the plates, you use the normalized parquet files. Is there a specific reason for this?

2024-05-21 16:49 UTC, jenna-tomkinson commented on 1.train_models/classify_genotypes/nbconverted/classify_genotypes.py
> +rng = np.random.default_rng(0)
Recommend including a code comment on what this is for. Is this the same as setting a random seed for reproducibility?

2024-05-21 16:49 UTC, jenna-tomkinson commented on 1.train_models/classify_genotypes/nbconverted/classify_genotypes.py
> +    Shuffle the columns of the input dataframe independently.
Recommend keeping the code strings similar across functions, e.g., include a short summary of the function for all function not just shuffle_data. Totally optional.

2024-05-21 16:49 UTC, jenna-tomkinson commented on 1.train_models/classify_genotypes/nbconverted/classify_genotypes.py
> +# ## Harmonize data across plates to each data split
Recommend not using the term "Harmonize" if you are not using a batch correction method. It looks like below that you are just taking the union of the features across all the plates and then concat all data together based on the split.

2024-05-21 16:49 UTC, jenna-tomkinson commented on 1.train_models/classify_genotypes/nbconverted/classify_genotypes.py
> +plate4df_path = pathlib.Path(root_dir / "nf1_painting_repo/3.processing_features/data/single_cell_profiles/Plate_4_sc_feature_selected.parquet").resolve(strict=True)
I see you state above, "The feature selected data is used in all data splits.", so I am assuming you want to have all plates with feature selected data not just Plate_4.

2024-05-22 14:30 UTC, jenna-tomkinson approved these changes
LGTM! 🎉 Feel free to merge! Just one question, how many features are we training on? I didn't see that in the notebook unless I missed it.

2024-05-22 16:32 UTC, MattsonCam commented
> LGTM! 🎉 Feel free to merge! Just one question, how many features are we training on? I didn't see that in the notebook unless I missed it.

There are 845 features used for training. Maybe I'll mention that in the README later

2024-05-22 16:32 UTC, MattsonCam commented
Thanks @jenna-tomkinson, merging now!

2024-05-22 16:32 UTC, merged